### PR TITLE
Fixed spawn item COUNT property and some compiler warnings (casts).

### PR DESCRIPTION
**Pull request by cbnolok**

### CODE REVIEW

**Comment by cbnolok** [comment]
You are right, that's was exactly the code i tried before realizing that, for some unknown reason and without any error, it didn't work. When i first restarted the server, all the npcs were dead or with a strange hits value, and most of times setting to the living ones hits = 20 resulted in their death. I have set the mana to 20, did .xshow 20, which showed mana = 0. Tried to fire an EventWarn, which showed that the result of that expression was 0. I tried also to use "minimum" in the code i submitted but i have similarly got weird values, so switched to a qval-like syntax, which appears to work. I can't explain why this is happening lol.
The only thing on which i'm not sure is the behaviour of GetArgVal when there aren't args, so i used HasArgs (which was also used in other parts of code in the same file).

**Comment by coruja747** [comment]
nah I tested it here and strangely it really break the value to 0, making it set HITS=0 on all chars. I already tested some workarounds here but nothing works

anyway, I think it's better we try to find a way to get this short working correctly instead use a workaroud which will move the long value to a new long, that uses short length manually and will be changed to short on static_cast. Although maybe it works, this doesn't make sense :P

**Comment by cbnolok** [comment]
I agree, this doesn't make sense. At least, this way works, i suggest to
merge it and to change it when someone finds a way to code these lines
better :D

**Comment by cbnolok** [comment]
Since XuN already fixed the casts i changed in this commit, i'll send another pull request with the remaining fixes.

**Pull request closed without merging**
