### PR TITLE
Fixed a bug with values RETURNed by triggers fired from scripts with TRIGGER keyword.

### PR DESCRIPTION
**Pull request by cbnolok**
Fixed: In certain situations returning 0 inside a custom trigger caused TRIGGER keyword to return 2. Also, potentially every value between 0-8 could interfere with some internal check. Now any value < 100 can be safely returned and readed.

### CODE REVIEW

**Comment by lintax** [comment]
What if some admin intentionally used return 2?

**Comment by cbnolok** [comment]
It didn't change the behaviour of the script parsing and it wouldn't change
it now. The best solution would be to store the returned (int) value in a
separate variable, but it would require lots of changes, i would be
satisfied to only avoid returning values which interfered with parsing.

**Comment by lintax** [comment]
As far as I understand your change, all old scripts that intentionally did "return 2" to make sphere to execute default return action will have undesired unexpected side effects, since will return value different from TRIIGRET_TYPE_DEFAULT
Same does with "return 1"
Correct me if I am wrong and your tests shows that the problem does not exists.

**Comment by cbnolok** [comment]
Afaik the TRIGRET values were never documented and no one knew that you could change internal behaviour by returning 2 or 0.
From the wiki: TRIGGER trig_name, trig_type R Fires a custom trigger and returns the RETURN value.
So TRIGGER was already supposed to return the script's RETURN value, not the TRIGRET value, which is instead used internally to know if the script returned or not a value and other things. Returning 8 meant returning TRIGRET_CONTINUE, why one would ever pass this to the parsing engine? And anyone knew that you could signal TRIGRET_CONTINUE to the parsing engine?

This said, look at https://github.com/Sphereserver/Source/blob/master/src/graysvr/CCharact.cpp#L3720.
If you return 0 or 2 in an EVENT, the parsing engine will not stop and continue to parse TEVENTS, CHARDEF triggers, EVENTSPET/EVENTSPLAYER and we don't want this because if i return a value nothing else should be done, and if i returned 0 and there was a RETURN 3 inside a TEVENTS, the TRIGGER keyword would return 3 instead of 0 (just speculating, i didn't test if that's happening actually). Anyone did know that you can do the engine acting like this? Would be convenient to permit such behaviour? I think not.

The only test i did tbh was to check if the return values i talked about in the issue i opened time ago worked, and they worked. Btw looking at the code i saw that another change is needed :D

**Comment by lintax** [comment]
I am mostly concerned with "return 1" (and probably "return 0") to continue working like it was before, since this is a commonly used and suggested way to writing custom code modifying sphere mechanics..
Surely, hardly anyone used "return 2" (I used but do not count upon), using just "return" that would continue to work correctly even if constants being changed.

**Comment by cbnolok** [comment]
You are right, it breaks the old behaviour and it requires using the new return values, which is bad (and ugly). Also, i thought about it and there's no point on using triggers the way i suggested here: https://github.com/Sphereserver/Source/issues/30. Custom triggers need also to behave like the default ones, with return 1 stopping the parsing chain and return 0/2 stopping the current trigger but allowing the same trigger to fire in the lower priority rings of the chain (chardef, events, etc). There are other ways to do what i want and the best thing is to leave triggers as they are now. You can drop this pull request, thanks!

**Pull request closed without merging**
