### PR TITLE
Renamed 0.56c to 0.56d

### PR DESCRIPTION
**Pull request by coruja747**
Maybe it's time to move? :P

PS: I don't want make this change on 'master' branch by myself, so using pull request others devs can review and decide if we can merge it or not

### CODE REVIEW

**Comment by nefthon** [comment]
I agree, it's been a time since 56c release, a new version was needed. Also with the move to git and the source release ... it looks like 'the moment' to do so.

**Comment by TorbenF** [comment]
Make sure Sphere is stable, create a tag and build a proper prerelease (http://prerelease.sphere.torfo.org/)

**Comment by Ben1028** [comment]
I would recommend getting it as stable as possible too before a version change.
I can take care of building the prereleases

**Comment by coruja747** [comment]
Build 2429 is pretty stable here, I'm using it on my live server with 120 players every day and current uptime is 9 days (and probably it would be more if I didn't had manually restarted it)

but anyway maybe it's better check again on builds 2470+ since last week it got many changes on source :P

**Comment by coruja747** [comment]
Too many commits ahead this branch, things are getting messed. I will delete this branch and keep the pull request closed to reopen again later

**Pull request closed without merging**
